language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.4.0"
  - travis_retry composer install --prefer-source --no-interaction

script: vendor/bin/phpunit --verbose

matrix:
  fast_finish: true
